name: FL Repo Updater
run-name: ${{ github.actor }} 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Download FlashLauncher
        run: wget https://github.com/FlashLauncher/releases/latest/download/FlashLauncher.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download AdvancedAPICore
        run: gh release download -R FlashLauncher/AdvancedAPICore -p AdvancedAPICore.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Start
        run: java -Dtoken="Bearer ${{ secrets.GITHUB_TOKEN }}" -cp "FlashLauncher.jar:AdvancedAPICore.jar:generator/src" Main.java