name: FL Repo Updater
run-name: ${{ github.actor }} 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Download FlashLauncher
        run: gh release download --repo FlashLauncher/FlashLauncher --pattern FlashLauncher.jar --dir ~
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download AdvancedAPICore
        run: gh release download --repo FlashLauncher/AdvancedAPICore --pattern AdvancedAPICore.jar --dir ~
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Set up
        run: mkdir ~/build
      - run: echo ~ >> $path

      - name: Build
        run: javac -d "${{ env.path }}/build" -classpath "${{ env.path }}/FlashLauncher.jar:${{ env.path }}/AdvancedAPICore.jar" -sourcepath generator/src generator/src/*.java

      - name: Start
        run: java -Dtoken="Bearer ${{ secrets.GITHUB_TOKEN }}" -cp "${{ env.path }}/FlashLauncher.jar:${{ env.path }}/AdvancedAPICore.jar:${{ env.path }}/build" Main