name: FL Repo Updater
run-name: ${{ github.actor }} 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Download FlashLauncher
        run: gh release download --repo FlashLauncher/FlashLauncher --pattern FlashLauncher.jar --dir ~
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download AdvancedAPICore
        run: gh release download --repo FlashLauncher/AdvancedAPICore --pattern AdvancedAPICore.jar --dir ~
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Set up
        run: mkdir ~/build
      - run: echo "path=$HOME" >> $GITHUB_ENV

      - name: Build
        run: javac -d "${{ env.path }}/build" -classpath "${{ env.path }}/FlashLauncher.jar:${{ env.path }}/AdvancedAPICore.jar" -sourcepath generator/src generator/src/*.java

      - name: Start
        run: java -Dtoken="${{ secrets.GITHUB_TOKEN }}" -cp "${{ env.path }}/FlashLauncher.jar:${{ env.path }}/AdvancedAPICore.jar:${{ env.path }}/build" Main

      - name: Push
        run: |
          git config user.name "Repo Updater Bot"
          git config user.email "<>"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add main/*
          git add user/*
          git diff --quiet && git diff --staged --quiet || git commit -am '[Update repo]'
          git push