name: FL Repo Updater
run-name: ${{ github.actor }} 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setup ${{ github.repository }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Download FlashLauncher
        run: gh release download -R FlashLauncher/FlashLauncher -p FlashLauncher.jar

      - name: Started
        run: java -Dtoken="Bearer ${{ secrets.GITHUB_TOKEN }}" -cp "FlashLauncher.jar:AdvancedAPICore.jar:generator/src" Main.java