name: FL Repo Updater
run-name: ${{ github.actor }} 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Download FlashLauncher
        run: gh release download --repo FlashLauncher/FlashLauncher --pattern FlashLauncher.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download AdvancedAPICore
        run: gh release download --repo FlashLauncher/AdvancedAPICore --pattern AdvancedAPICore.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Set up
        run: mkdir build

      - name: Build
        run: javac -d build -cp "FlashLauncher.jar:AdvancedAPICore.jar" -sourcepath generator/src *.java

      - name: Start
        run: java -Dtoken="Bearer ${{ secrets.GITHUB_TOKEN }}" -cp "FlashLauncher.jar:AdvancedAPICore.jar:build" Main