name: FL Repo Updater
run-name: ${{ github.actor }} 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setup"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '21'
      - uses: dawidd6/action-download-artifact@v3
        with:
          name: FlashLauncher.jar
          repo: FlashLauncher/FlashLauncher
          skip_unpack: true
      - uses: dawidd6/action-download-artifact@v3
        with:
          name: AdvancedAPICore.jar
          repo: FlashLauncher/AdvancedAPICore.jar
          skip_unpack: true
      - run: echo "Started"
      - run: java -Dtoken="Bearer ${{ secrets.GITHUB_TOKEN }}" -cp "FlashLauncher.jar:AdvancedAPICore.jar:generator/src" Main.java