name: FL Repo Updater
run-name: ${{ github.actor }} 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setup"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
      - run: echo "Started"
      - run: java generator/src/Main.java